# Generated by Django 6.0 on 2025-12-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='piececover',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
